apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: my-rabbitmq

  name: my-rabbitmq
  namespace: squidgame
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-rabbitmq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-rabbitmq
      
    spec:
      containers:
      - image: rabbitmq:3-management-alpine
        name: server-rabbit
        ports:
          - containerPort: 5672
          - containerPort: 15672     
        resources: {}   
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: my-rabbitmq
  name: my-rabbitmq
  namespace: squidgame
spec:
  type: NodePort
  ports:
  - port: 5672
    protocol: TCP
    targetPort: 5672
  selector:
    app: my-rabbitmq
  
status:
  loadBalancer: {}
